toolbox:
  - /toolbox/handle
  - /toolbox/side_front
  - /toolbox/side_back
  - /toolbox/side_left
  - /toolbox/side_right
romeo:
  - /romeo/pan
  - /romeo/hot_plate
  - /romeo/bowl
  - /romeo/cover
  - /romeo/drugs
  - /romeo/juice
  - /romeo/tray
  - /romeo/glass
