# SetNewTrainingExample: Updates the learner with a reward

# The state of the scene and command (un)validated
SceneState scene_state
MDPAction action
MDPAction predicted_action
bool corrected
float64 prediction_confidence
---
# No return parameter

